Update webdav-test

diff --git a/webdav-test b/webdav-test
--- a/webdav-test
+++ b/webdav-test
@@ -6,6 +6,8 @@ TEST_DOC=${TEST_DIR}/${TEST_FILENAME}
 TEMP_DIR=/tmp
 TEMP_DOC=${TEMP_DIR}/${TEST_FILENAME}
 DOCBOOK_HTML_XSL=/usr/share/sgml/docbook/xsl-stylesheets-1.75.2/html/docbook.xsl
+DOCBOOK_DTD=/usr/share/sgml/docbook/xml-dtd-4.5-1.0-51.el6/docbookx.dtd
+JING_JAR=/home/mcaspers/Applications/jing-20091111/bin/jing.jar
 
 #sudo mount.davfs http://skynet-dev.usersys.redhat.com:8080/pressgang-ccms-webdav /mnt/pressgang -o uid=matthew
 
@@ -141,6 +143,22 @@ diff /tmp/docbook1.html /tmp/docbook2.html
 if [[ $? -ne 0 ]]
 then
 	echo "************ xsltproc test 1 failed ************"
+fi
+
+# jing test 1
+echo Starting jing test 1
+echo '<!DOCTYPE article PUBLIC '-//OASIS//DTD DocBook XML V4.5//EN' 'http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd'>
+<article><title>test</title><para>hi</para></article>' > "${TEMP_DOC}"
+echo '<!DOCTYPE article PUBLIC '-//OASIS//DTD DocBook XML V4.5//EN' 'http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd'>
+<article><title>test</title><para>hi</para></article>' > "${TEST_DOC}"
+java -jar "${JING_JAR}" "${TEMP_DOC}" "${DOCBOOK_DTD}" > /tmp/jing1.tmp
+java -jar "${JING_JAR}" "${TEST_DOC}" "${DOCBOOK_DTD}" > /tmp/jing2.tmp
+
+diff /tmp/jing1.html /tmp/jing2.html
+
+if [[ $? -ne 0 ]]
+then
+	echo "************ jing test 1 failed ************"
 fi
 
 
