fixed test script

diff --git a/webdav-test b/webdav-test
--- a/webdav-test
+++ b/webdav-test
@@ -184,8 +184,8 @@ echo '<section></section1>' > "${TEST_DOC}"
 xmllint --valid "${TEMP_DOC}" 2> /tmp/xml1.tmp
 xmllint --valid "${TEST_DOC}" 2> /tmp/xml2.tmp
 
-sed -i -e 's#${TEMP_DOC}##g' /tmp/xml1.tmp
-sed -i -e 's#${TEST_DOC}##g' /tmp/xml2.tmp
+sed -i -e 's#'${TEMP_DOC}'##g' /tmp/xml1.tmp
+sed -i -e 's#'${TEST_DOC}'##g' /tmp/xml2.tmp
 
 diff /tmp/xml1.tmp /tmp/xml2.tmp
 
@@ -219,6 +219,19 @@ diff "${TEST_DOC}" "${TEMP_DOC}"
 if [[ $? -ne 0 ]]
 then
 	echo "************ sed test 1 failed ************"
+fi
+
+# tar test 1
+echo Starting tar test 1
+echo '<!-- sed test -->' > "${TEMP_DOC}"
+echo '<!-- sed test -->' > "${TEST_DOC}"
+tar -C "${TEMP_DIR}" -cjf /tmp/tar1.tar.bz2 "${TEMP_DOC}"
+tar -C "${TEST_DIR}" -cjf /tmp/tar2.tar.bz2 "${TEST_DOC}"
+diff /tmp/tar1.tar.bz2 /tmp/tar2.tar.bz2
+
+if [[ $? -ne 0 ]]
+then
+	echo "************ tar test 1 failed ************"
 fi
 
 # vi test 1
@@ -311,17 +324,17 @@ echo '<section><title>Test</title><para>hi</para></section>' > "${TEST_DOC}"
 
 cd /tmp
 rm -rf book
-publican create --name=book
+publican create --name=book > /dev/null 2>&1
 echo '<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE bookinfo PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" [<!ENTITY % BOOK_ENTITIES SYSTEM "book.ent">%BOOK_ENTITIES;]><chapter><title>Book</title><xi:include href="'${TEMP_DOC}'" xmlns:xi="http://www.w3.org/2001/XInclude"/></chapter>' > /tmp/book/en-US/Chapter.xml
 cd /tmp/book
-publican build --langs=en-US --formats=html-single
+publican build --langs=en-US --formats=html-single > /dev/null 2>&1
 
 cd /tmp
 rm -rf bookwebdav
-publican create --name=bookwebdav
+publican create --name=bookwebdav > /dev/null 2>&1
 echo '<?xml version="1.0" encoding="utf-8" ?><!DOCTYPE bookinfo PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd" [<!ENTITY % BOOK_ENTITIES SYSTEM "book.ent">%BOOK_ENTITIES;]><chapter><title>Book</title><xi:include href="'${TEST_DOC}'" xmlns:xi="http://www.w3.org/2001/XInclude"/></chapter>' > /tmp/bookwebdav/en-US/Chapter.xml
 cd /tmp/bookwebdav
-publican build --langs=en-US --formats=html-single
+publican build --langs=en-US --formats=html-single > /dev/null 2>&1
 
 # the id and href attributes change, as well as the book title and entity references
 sed -i -e 's/id=\".*\"//g' /tmp/bookwebdav/tmp/en-US/html-single/index.html
