Working on test script

diff --git a/webdav-test b/webdav-test
--- a/webdav-test
+++ b/webdav-test
@@ -67,10 +67,24 @@ then
 	echo "************ grep test 1 failed ************"
 fi
 
+# xmllint test 1
+echo Starting xmllint test 1
+echo '<section></section1>' > "${TEMP_DOC}"
+echo '<section></section1>' > "${TEST_DOC}"
+xmllint --valid "${TEMP_DOC}" 2> /tmp/xml1.tmp
+xmllint --valid "${TEST_DOC}" 2> /tmp/xml2.tmp
+
+diff /tmp/xml1.tmp /tmp/xml2.tmp
+
+if [[ $? -ne 0 ]]
+then
+	echo "************ xmllint test 1 failed ************"
+fi
+
 # xmllint test 2
 echo Starting xmllint test 2
-echo '<section></section>' &> "${TEMP_DOC}"
-echo '<section></section>' &> "${TEST_DOC}"
+echo '<section></section>' > "${TEMP_DOC}"
+echo '<section></section>' > "${TEST_DOC}"
 xmllint --output "${TEMP_DOC}" "${TEMP_DOC}"
 xmllint --output "${TEST_DOC}" "${TEST_DOC}"
 
